version: "3.9"

services:
  app:
    build: .
    container_name: zero-trust-gateway
    ports:
      - "8501:8501"
    volumes:
      - ./shared_data:/app/shared_data
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.headless=true
    restart: unless-stopped
